services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:Z
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
    volumes:
      - db_data:/var/lib/mysql:Z

  composer:
    image: composer:latest
    volumes:
      - .:/app:Z
    working_dir: /app

  dbhub:
    image: docker.io/bytebase/dbhub
    ports:
      - "8081:8080"
    command:
      - "--transport"
      - "http"
      - "--port"
      - "8080"
      - "--dsn"
      - "mysql://root:root@db:3306/my_db"
    depends_on:
      - db

volumes:
  db_data:
